language: node_js
node_js:
  - "node"
  - "lts/*"
cache: npm
jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: npm install
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - npm test
        - echo "Report Coverage..."
        - npm run coveralls
    - stage: publish
      name: "Publish to NPM"
      node_js: 'node'
      script: echo "Publishing to NPM..."
      deploy:
        provider: npm
        email: vasudevan.palani@gmail.com
        api_key:
          secure: "h3zaONk8Jd4qjUbSEMFOSLWZjZ2wv8CVT07j3O3a0uOHrSjRzqxAIQapS9DSblt+jwY5agGflwcRYYNmKrvqou6zgfxEkFoL2+ay4bjlLnvtUJG+Xyug17SbhjldTtljgBkz22SMgJujOR6GXCQDdVwKmY7/pc2OLgraf55VHB0nRNxmktNrOqaPGuz8EaFS5Z1Xgz9rXuC1uhsrPjClLa7jdkbbtd6tdqnT+YFfDPDChOzSJWI4MI0ZP88odiuPdnFHP1Fc7Jd4Cn7beCSzPBpZ4CrwsJtKqnitugiVtR/QA9by3vgym43WSYpBXbIzti2ZmMxt9l6cyxi/n282bb58lemQIQ9OfJ4cPCDlQKSrCKlkZuoUWz1Bs6hAuoWHbthVZ743ceafehqrXt+zdh5JxFeS/Ifi+6hlVDmW/PYFm3wC6S0XjAQbfZ3EXUQzhcqHRM25EVOVyAq9Sf21HZMfnp7mDUc0rqdVVUB4W0TF4VP2McV52pTmC0CLZTimjRe2pZMBpPRYgVupgEH04UOvHNzs/lLh1kL29ZSX6vxNfZNJiFtOojt1Kgke8x7HzGgNKprqRXuvGVwml0idjkdQ4hFLryp3Cp5jYzLplXHKR/uG/rPD7QGszKKEbMZf80JerUHu62YOWLXcL7jgv37UbtoGGN6xmfsHF0xe4SY="
        on:
          branch: master
          tags: true
          condition: -z $SKIP_PUBLISH
stages:
  - install
  - test
  - publish

